version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - |
        if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
          echo "Error: DOCKER_USERNAME or DOCKER_PASSWORD not set in environment variables."
          exit 1
        fi
      - echo "Logging in as $DOCKER_USERNAME..."
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      - echo Building backend image...
      - docker build -t $DOCKER_USERNAME/devops-backend ./backend

      - echo Building frontend image...
      - docker build -t $DOCKER_USERNAME/devops-frontend ./frontend

  post_build:
    commands:
      - echo Pushing backend image...
      - docker push $DOCKER_USERNAME/devops-backend

      - echo Pushing frontend image...
      - docker push $DOCKER_USERNAME/devops-frontend

      - echo Build completed successfully!
