version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      - echo Building backend image...
      - docker build -t mallesh2210/devops-backend ./backend

      - echo Building frontend image...
      - docker build -t mallesh2210/devops-frontend ./frontend

  post_build:
  commands:
    - echo "Creating SSH key..."
    - echo "$EC2_KEY_B64" | base64 -d > key.pem
    - chmod 600 key.pem
    - echo "Deploying to EC2..."
    - ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "
        cd ~/Devops-assessment &&
        git pull origin main &&
        docker-compose down &&
        docker-compose up -d --build
      "
