version: "3"

services:
  backend:
    image: mallesh2210/devops-backend:latest
    container_name: devops_backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=production-secret-key-123
      - DEBUG=False
      - ALLOWED_HOSTS=*
    restart: unless-stopped

  frontend:
    image: mallesh2210/devops-frontend:latest
    container_name: devops_frontend
    ports:
      - "3000:8080"
    depends_on:
      - backend
    restart: unless-stopped
